### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by McMelonTV** [Herobrine643928/Chest-UI#1]
Why not use the built in vanilla hover text renderer? Its a lot more "fluid". Your hovertext is pretty janky

https://github.com/Herobrine643928/Chest-UI/assets/62901799/42268ceb-02ea-469c-a601-f6cf214db9b6

in the video you can see that yours hops up and down a bit while the vanilla one doesnt

**Comment by LeGend077** [comment]
Thanks! This issue will be fixed soon as possible.

**Comment by LeGend077** [comment]
_fixed_

**Comment by LeGend077** [comment]
_fixed_
