### ISSUE TITLE
item textures are still flipped

### ISSUE THREAD

**Issue by ModdedPro14** [Herobrine643928/Chest-UI#11]
i know i already have reported this but just wanna make sure it all gets fixed because i love this chest ui so much but some textures are still flipped like the water bucket and the dark oak sign
![Screenshot_2023-08-15_152805](https://github.com/Herobrine643928/Chest-UI/assets/101987712/33165934-3e48-4ae4-a038-f3fafb538011)
![Screenshot_2023-08-15_152814](https://github.com/Herobrine643928/Chest-UI/assets/101987712/d83ccdad-d7e5-4203-9226-d69f4999e1eb)

i hope this gets fixed and thank you!

**Comment by jaminNZx** [comment]
this is still an issue
