### ISSUE TITLE
When specifying a path from the 'textures' folder, it does not appear as enchanted.

### ISSUE THREAD

**Issue by oasoobi** [Herobrine643928/Chest-UI#19]
example
`.button(1, "§l§bKIT", [], "textures/items/diamond", 1, true)`

![image](https://github.com/Herobrine643928/Chest-UI/assets/134684352/d52c97fe-7e84-4c79-b9bb-379e519bf998)

**Comment by Herobrine643928** [comment]
Works as intended. The texture paths are static and do not support the enchant glint.
