### ISSUE TITLE
NaN bug

### ISSUE THREAD

**Issue by McMelonTV** [Herobrine643928/Chest-UI#8]
![image](https://github.com/Herobrine643928/Chest-UI/assets/62901799/c507acfa-530e-48d4-ac51-a7822e75e9d0)
there should be an isNaN check for the amount when adding the buttons

**Comment by Herobrine643928** [comment]
Fixed in latest commits, thanks :)

**Comment by Herobrine643928** [comment]
Fixed in latest commits, thanks :)
